### PR TITLE
Created Database

### LINKED ISSUE #3: Create dummy data
- [ ] create 5 sample actors 
- [ ] create 5 sample genres
- [ ] create 5 sample shows

### PR DESCRIPTION
**Pull request by Jadechoa**
Closes #3

### CODE REVIEW

**Review by devans0507 — COMMENTED** [review]
great

**Review by Jadechoa — COMMENTED** [review]
Approve!!!

**Review by cassandradunning — APPROVED** [review]
👍

**Review by devans0507 — APPROVED** [review]
Great work

**Review by WillJckson — APPROVED** [review]
Looks great.

**Pull request merged**
